# Linux Makefile for GVT
# Usage: make PLATFORM=linux|win in main GVT directory
# Default PLATFORM is linux

.PHONY: all clean

GO = go
OUT = bin/linux

all: clean build run

build: core/ core/cmd/ core/internal core/main.go
	mkdir -p $(OUT)
	mkdir -p out
	$(GO) build -o $(OUT)/gvt ./core
	echo "Done! Binary in $(OUT)/gvt"
	tar -czvf gvt-linux.tar.gz $(OUT)/gvt LICENSE README.md
	mv gvt-linux.tar.gz out/gvt-linux.tar.gz

clean:
	rm -rf $(OUT)/*

run: $(OUT)/gvt
	./$(OUT)/gvt